// GM Assistant Communication Studio — dark communication-board template
(() => {
  const comm = document.getElementById('comm');
  if (!comm) return;

  const css = `
  <style id="commStudioStyles">
    .comm-studio{display:grid;grid-template-columns:minmax(270px,.72fr) minmax(0,1.28fr);gap:16px;align-items:start}
    .comm-tools{position:sticky;top:78px}.comm-tools .card{margin-bottom:12px}.comm-actions,.comm-style-row{display:flex;gap:8px;flex-wrap:wrap}.comm-style-row button{border:1px solid var(--line);background:#fff;border-radius:999px;padding:8px 11px;font-weight:850}.comm-style-row button.active{background:#a8151b;color:#fff;border-color:#a8151b}.comm-note{font-size:12px;line-height:1.45;color:var(--muted);margin-top:8px}
    .poster-shell{background:#d8d0c8;border-radius:18px;padding:14px;overflow:auto}
    .team-poster{--red:#c71920;--gold:#f1c232;--green:#70ad47;--blue:#4b8dcc;position:relative;aspect-ratio:8.5/11;max-width:760px;margin:auto;overflow:hidden;color:#fff;background:radial-gradient(circle at 50% 0,#333 0,#181818 48%,#0b0b0b 100%);border:7px solid #111;box-shadow:0 18px 50px #0004;font-family:Arial,Helvetica,sans-serif;display:flex;flex-direction:column}
    .team-poster:before{content:'';position:absolute;inset:0;pointer-events:none;opacity:.16;background-image:repeating-linear-gradient(12deg,#fff0 0 16px,#fff 17px,#fff0 18px 34px);mix-blend-mode:overlay}
    .poster-top{position:relative;padding:22px 25px 12px;text-align:center;z-index:1}.brand-row{display:flex;justify-content:space-between;align-items:center;gap:10px}.brand-badge{font-size:14px;font-weight:1000;letter-spacing:.04em;color:#fff}.brand-badge.arbys{font-size:22px;color:#fff;text-shadow:2px 2px #a8151b}.brand-badge.amb{font-family:Georgia,serif;font-size:16px;color:#f5d338}.poster-title{font-size:clamp(34px,6vw,58px);font-weight:1000;line-height:.9;letter-spacing:-.04em;text-transform:uppercase;margin:3px 0 5px;font-style:italic}.poster-title .store-no{color:var(--red)}.poster-ribbon{display:inline-block;background:var(--red);padding:6px 24px;transform:skew(-5deg);font-size:19px;font-weight:1000;text-transform:uppercase}.poster-date{margin-top:7px;font-weight:900;font-size:14px;letter-spacing:.04em}
    .poster-body{position:relative;z-index:1;padding:8px 17px 12px;display:grid;grid-template-columns:1fr 1fr;gap:11px;flex:1;min-height:0}.board-card{background:#111d;border:2px solid #b71920;border-radius:10px;box-shadow:inset 0 0 0 1px #ffffff12;padding:11px}.board-card h3{margin:0 0 8px;font-size:17px;text-transform:uppercase;font-style:italic}.red-head{background:var(--red);margin:-11px -11px 10px;padding:8px 11px;border-radius:7px 7px 0 0}.hero-osat{display:flex;align-items:center;gap:12px}.score-ring{width:116px;height:116px;flex:0 0 116px;border:8px solid var(--red);border-right-color:#777;border-radius:50%;display:grid;place-items:center;text-align:center}.score-ring strong{font-size:43px;line-height:.9}.score-ring small{font-size:12px;font-weight:900}.goal-note{color:#ffd52f;font-size:14px;font-weight:1000}.metric-list{display:grid;gap:5px;flex:1}.metric-line{display:flex;justify-content:space-between;gap:8px;border-bottom:1px solid #ffffff25;padding:3px 0;font-size:12px;font-weight:850}.metric-line b{color:#ffd52f;font-size:15px}
    .ops-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.op{border:1px solid #ffffff22;border-radius:7px;padding:7px}.op span{display:block;font-size:9px;text-transform:uppercase;color:#ddd;font-weight:900}.op strong{font-size:19px}.op.hero{grid-column:1/-1}.op.hero strong{font-size:35px;color:#fff}.over{color:#ffcf33;font-weight:900;font-size:11px;margin-top:3px}
    .sticky{background:#f4c62e;color:#171717;transform:rotate(-1deg);border:0;box-shadow:3px 5px 0 #0007}.sticky h3{color:#a8151b}.sticky strong{color:#a8151b}.recognition{border-color:#d6a91b}.recognition h3{color:#ffd52f}.recognition .win{font-size:22px;font-weight:1000;font-style:italic}.opportunity{border-color:#e77b22}.opportunity h3{color:#ff9b3d}.opportunity .win{font-size:22px;font-weight:1000;font-style:italic;color:#ff9b3d}
    .focus{grid-column:1/-1}.focus-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.focus-item{display:flex;gap:8px;align-items:flex-start;background:#ffffff0d;border-radius:7px;padding:7px;font-size:11px;font-weight:800;line-height:1.25}.focus-num{width:24px;height:24px;flex:0 0 24px;border-radius:50%;display:grid;place-items:center;background:var(--red);font-size:13px}.focus-item:nth-child(2) .focus-num{background:#d8751b}.focus-item:nth-child(3) .focus-num{background:#2c6ca8}.focus-item:nth-child(4) .focus-num{background:#4f8c31}
    .shopper{grid-column:1/-1;background:#f2c733;color:#171717;border:0;transform:rotate(.3deg);padding:10px 13px}.shopper h3{color:#a8151b}.shopper-grid{display:grid;grid-template-columns:1fr 1fr;gap:4px 16px;font-size:11px;font-weight:850}.shopper-grid div:before{content:'✓ ';color:#a8151b;font-size:15px;font-weight:1000}.poster-footer{position:relative;z-index:1;background:linear-gradient(90deg,#7f080c,#d21f25,#7f080c);padding:10px 15px;text-align:center;font-size:18px;font-weight:1000;font-style:italic;text-transform:uppercase}.poster-footer span{color:#ffd52f}
    .team-poster.style-bold{--red:#e31d25}.team-poster.style-bold .board-card{background:#050505ee}.team-poster.style-motivational{--red:#b4151b;--gold:#ffd23c}.team-poster.style-motivational .poster-title{font-size:clamp(38px,6.5vw,62px)}.team-poster.style-clean{background:#f7f2e9;color:#171717;border-color:#d7cec4}.team-poster.style-clean:before{display:none}.team-poster.style-clean .board-card{background:#fff;color:#171717;border-color:#ddd}.team-poster.style-clean .metric-line{border-color:#ddd}.team-poster.style-clean .brand-badge{color:#171717}.team-poster.style-clean .brand-badge.arbys{color:#a8151b}.team-poster.style-clean .op span{color:#555}.team-poster.style-clean .focus-item{background:#f2eee8}
    @media(max-width:850px){.comm-studio{grid-template-columns:1fr}.comm-tools{position:static}}
    @media(max-width:540px){.poster-shell{padding:6px}.team-poster{font-size:90%}.poster-body{padding:6px 10px;gap:7px}.score-ring{width:88px;height:88px;flex-basis:88px}.score-ring strong{font-size:34px}.focus-grid{grid-template-columns:1fr}}
    @media print{body.poster-print *{visibility:hidden!important}body.poster-print #commPoster,body.poster-print #commPoster *{visibility:visible!important}body.poster-print #commPoster{position:absolute!important;left:0;top:0;width:8.5in!important;height:11in!important;max-width:none!important;box-shadow:none!important;border:0!important}body.poster-print .poster-shell{padding:0!important;background:#fff!important;overflow:visible!important}@page{size:letter portrait;margin:0}}
  </style>`;
  document.head.insertAdjacentHTML('beforeend',css);

  const topics={weekly:'Weekly Team Update',speed:'Speed of Service',guest:'Guest Experience',accuracy:'Accuracy',clean:'Cleanliness',mystery:'Mystery Shopper',food:'Food Variance',labor:'Labor',recognition:'Recognition',custom:'Custom Topic'};
  const latestWeek=()=>{try{return typeof latest==='function'?latest():null}catch{return null}};
  const val=(k,v)=>{try{return fmt(k,v)}catch{return v??'—'}};
  const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const cap=x=>x?x.charAt(0).toUpperCase()+x.slice(1):'';
  const guestKeys=['accuracy','cleanliness','speed','taste','friendliness'];
  const lowest=w=>{const a=guestKeys.filter(k=>w?.[k]!=null);return a.length?a.reduce((x,y)=>+w[x]<=+w[y]?x:y):null};
  const highest=w=>{const a=guestKeys.filter(k=>w?.[k]!=null);return a.length?a.reduce((x,y)=>+w[x]>=+w[y]?x:y):null};
  const dateRange=w=>{if(!w?.weekStart)return 'LATEST WEEK';try{return `${fd(w.weekStart)} – ${end(w.weekStart)}`}catch{return 'LATEST WEEK'}};
  const driveText=w=>w?.driveOverall!=null?val('driveOverall',w.driveOverall):'—';
  const goal=(k,fallback)=>s?.settings?.[k]??fallback;

  comm.innerHTML=`<div class="card hero" style="margin-bottom:14px"><div><div class="eyebrow">Communication Center</div><h2>Communication Creator</h2><p class="muted">Create the same bold communication-board style each week using your latest store numbers.</p></div><div class="hero-actions"><button class="primary" id="quickWeeklyPoster">Create Weekly Board</button></div></div><div class="comm-studio"><div class="comm-tools"><div class="card"><div class="eyebrow">Build your board</div><h2 style="margin-bottom:14px">Poster Builder</h2><label>Topic<select id="commTopic">${Object.entries(topics).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label style="margin-top:12px">Custom headline<input id="commHeadline" placeholder="Leave blank for Weekly Team Update"></label><label style="margin-top:12px">Custom team message<textarea id="commMessage" rows="3" placeholder="Optional message"></textarea></label><label style="margin-top:12px">Style</label><div class="comm-style-row" id="commStyles"><button type="button" data-style="fun" class="active">Board</button><button type="button" data-style="bold">Extra Bold</button><button type="button" data-style="motivational">Motivational</button><button type="button" data-style="clean">Clean</button></div><label style="display:flex;grid-template-columns:auto 1fr;align-items:center;gap:9px;margin-top:14px"><input id="commUseData" type="checkbox" checked style="width:auto">Use latest weekly data automatically</label><div class="comm-actions"><button class="primary" type="button" id="commGenerate">Generate Board ✨</button><button class="secondary" type="button" id="commShuffle">Change Style</button><button class="secondary" type="button" id="commPrint">Print</button></div><div class="comm-note">Designed for an 8.5 × 11 communication board. Weekly data fills in automatically.</div></div></div><div class="poster-shell"><div id="commPoster" class="team-poster style-fun"></div></div></div>`;

  let selectedStyle='fun';
  const topicEl=document.getElementById('commTopic'),headlineEl=document.getElementById('commHeadline'),msgEl=document.getElementById('commMessage'),useDataEl=document.getElementById('commUseData'),poster=document.getElementById('commPoster');

  function focusItems(w){
    const low=lowest(w), dg=+goal('driveGoal',60), drive=+w?.driveOverall, laborGoal=+goal('laborGoal',40), labor=+w?.laborHoursSaved;
    return [
      `Keep OSAT at ${goal('osatGoal',55)}% or higher. ${low?`Focus on ${cap(low)} (${val(low,w[low])}).`:''}`,
      Number.isFinite(drive)?`Drive-thru: ${driveText(w)}. ${drive>dg?`${Math.round(drive-dg)} sec over goal — review slow dayparts.`:'Goal met — protect the pace.'}`:'Stay positioned and peak-ready.',
      w?.foodVariance!=null?`Food variance: ${val('foodVariance',w.foodVariance)}. Review waste, portions, transfers and top losses.`:'Protect portions and waste routines.',
      Number.isFinite(labor)?`Labor saved: ${val('laborHoursSaved',labor)}. ${labor>=laborGoal?'On track — protect service.':`${Math.max(0,laborGoal-labor)} hrs short of goal.`}`:'Protect service while managing labor.'
    ];
  }

  function renderPoster(){
    const w=useDataEl.checked?latestWeek():null, low=lowest(w), hi=highest(w), osat=w?.osat!=null?w.osat:'—', osatGoal=goal('osatGoal',55), store=s?.settings?.storeNumber||'8571';
    const custom=msgEl.value.trim();
    const shopper=['Be friendly','Offer a Meal','Ask if they want to upsize to LG/XL','Suggestive sale a turnover','Offer sauce','Repeat the Order for Accuracy','Give the total and Thanks'];
    const title=headlineEl.value.trim()||topics[topicEl.value]||'Weekly Team Update';
    poster.className=`team-poster style-${selectedStyle}`;
    poster.innerHTML=`<div class="poster-top"><div class="brand-row"><div class="brand-badge arbys">Arby’s</div><div class="brand-badge amb">☀ AMBROSIA QSR</div></div><div class="poster-title">STORE <span class="store-no">${esc(store)}</span></div><div class="poster-ribbon">${esc(title)}</div><div class="poster-date">${esc(dateRange(w))}</div></div><div class="poster-body">
      <section class="board-card"><h3 class="red-head">★ Guest Experience</h3><div class="hero-osat"><div class="score-ring"><div><small>OSAT</small><br><strong>${esc(osat)}${osat==='—'?'':'%'}</strong><br><small>GOAL ${esc(osatGoal)}%</small></div></div><div class="metric-list">${guestKeys.map(k=>`<div class="metric-line"><span>${cap(k)}</span><b>${w?.[k]!=null?esc(val(k,w[k])):'—'}</b></div>`).join('')}</div></div></section>
      <section class="board-card"><h3 class="red-head">⚙ Operations</h3><div class="ops-grid"><div class="op hero"><span>Drive-Thru Overall</span><strong>${esc(driveText(w))}</strong><div class="over">GOAL ${esc(val('driveOverall',goal('driveGoal',60)))}</div></div><div class="op"><span>Food Variance</span><strong>${w?.foodVariance!=null?esc(val('foodVariance',w.foodVariance)):'—'}</strong></div><div class="op"><span>Labor Saved</span><strong>${w?.laborHoursSaved!=null?esc(val('laborHoursSaved',w.laborHoursSaved)):'—'}</strong></div><div class="op"><span>Weekly Sales</span><strong>${w?.weeklySales!=null?esc(val('weeklySales',w.weeklySales)):'—'}</strong></div></div></section>
      <section class="board-card recognition"><h3>🏆 Recognition</h3><div class="win">${hi?`${cap(hi)} is our STRONGEST guest category!`:'Celebrate the team’s strongest win!'}</div><p>${hi?`Great work at ${esc(val(hi,w[hi]))}. Keep it going!`:'Recognize great execution this week.'}</p></section>
      <section class="board-card opportunity"><h3>↗ Opportunity</h3><div class="win">${low?`${cap(low)} is our LOWEST guest category.`:'Find the clearest opportunity.'}</div><p>${low?'Coach one simple behavior every shift.':'Choose one behavior to improve this week.'}</p></section>
      <section class="board-card focus"><h3 class="red-head">🎯 This Week’s Focus</h3><div class="focus-grid">${focusItems(w).map((x,i)=>`<div class="focus-item"><div class="focus-num">${i+1}</div><div>${esc(x)}</div></div>`).join('')}</div>${custom?`<p style="margin:9px 0 0;font-weight:900;color:#ffd52f">Manager note: ${esc(custom)}</p>`:''}</section>
      <section class="board-card shopper"><h3>🔎 BE READY FOR THE MYSTERY SHOPPER!</h3><div class="shopper-grid">${shopper.map(x=>`<div>${esc(x)}</div>`).join('')}</div></section>
    </div><div class="poster-footer">FAST. ACCURATE. CLEAN. FRIENDLY. <span>EVERY GUEST. EVERY TIME.</span></div>`;
  }

  document.getElementById('commStyles').addEventListener('click',e=>{const b=e.target.closest('button[data-style]');if(!b)return;selectedStyle=b.dataset.style;document.querySelectorAll('#commStyles button').forEach(x=>x.classList.toggle('active',x===b));renderPoster()});
  document.getElementById('commGenerate').onclick=renderPoster;
  document.getElementById('commShuffle').onclick=()=>{const all=['fun','bold','motivational','clean'];selectedStyle=all[(all.indexOf(selectedStyle)+1)%all.length];document.querySelectorAll('#commStyles button').forEach(x=>x.classList.toggle('active',x.dataset.style===selectedStyle));renderPoster()};
  document.getElementById('quickWeeklyPoster').onclick=()=>{topicEl.value='weekly';headlineEl.value='';msgEl.value='';useDataEl.checked=true;renderPoster();document.querySelector('.poster-shell')?.scrollIntoView({behavior:'smooth',block:'start'})};
  document.getElementById('commPrint').onclick=()=>{document.body.classList.add('poster-print');window.print();setTimeout(()=>document.body.classList.remove('poster-print'),500)};
  [topicEl,headlineEl,msgEl,useDataEl].forEach(el=>el.addEventListener(el.tagName==='SELECT'||el.type==='checkbox'?'change':'input',renderPoster));
  renderPoster();
})();